---
- name: Provisioning Servers
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: us-east-1
    instance_type: t2.micro
    ami_id: ami-0c7217cdde317cfec
    
    vpc_subnets: ["subnet-0c61829158e8e4d4c", "subnet-0b1ab377154066118"] 
    
    vpc_id: "vpc-0b5f4a452fa240cf9"

  tasks:
    - name: 1. Target Group for Web Tier
      community.aws.elb_target_group:
        name: Web-Target-Group
        protocol: http
        port: 80
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}" 
        health_check_path: /
        health_check_protocol: http
        state: present
      register: target_group

    - name: 2. Application Load Balancer
      community.aws.elb_application_lb:
        name: Web-ALB
        region: "{{ aws_region }}"
        security_groups: ["ALB-SG"]
        subnets: "{{ vpc_subnets }}"
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: Web-Target-Group
        state: present

    - name: 2.5 Gather Web-SG ID for Launch Template
      amazon.aws.ec2_security_group_info:
        region: "{{ aws_region }}"
        filters:
          group-name: Web-SG
      register: web_sg_info

    - name: 3. Launch Template (Web Server)
      amazon.aws.ec2_launch_template:
        name: Web-Server-Template
        region: "{{ aws_region }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        security_group_ids: ["{{ web_sg_info.security_groups[0].group_id }}"]
        state: present

    - name: 4. Auto Scaling Group (The Cloning Machine)
      amazon.aws.ec2_asg:
        name: Web-ASG
        region: "{{ aws_region }}"
        launch_template:
          launch_template_name: Web-Server-Template
        health_check_type: ELB
        health_check_period: 300
        min_size: 1
        max_size: 5
        desired_capacity: 0
        target_group_arns: ["{{ target_group.target_group_arn }}"]
        vpc_zone_identifier: "{{ vpc_subnets }}"
        state: present

    - name: 5. Provision App Server
      amazon.aws.ec2_instance:
        name: "App-Server"
        region: "{{ aws_region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_groups: ["App-SG"]
        wait: true

    - name: 6. Provision Database Server
      amazon.aws.ec2_instance:
        name: "Database-Server"
        region: "{{ aws_region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        security_groups: ["Database-SG"]
        wait: true
